<?php
/**
 * Seo
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  NFQ\KunstmaanRestApi\PhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Šiaulių Bankas REST API
 *
 * Šiaulių Bankas REST API provides secure and efficient access to application data, enabling seamless data synchronization between Šiaulių Bankas and external systems.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NFQ\KunstmaanRestApi\PhpClient\Model;

use \ArrayAccess;
use \NFQ\KunstmaanRestApi\PhpClient\ObjectSerializer;

/**
 * Seo Class Doc Comment
 *
 * @category Class
 * @package  NFQ\KunstmaanRestApi\PhpClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Seo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Seo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'metaTitle' => 'string',
        'metaDescription' => 'string',
        'metaAuthor' => 'string',
        'metaRobots' => 'string',
        'ogType' => 'string',
        'ogTitle' => 'string',
        'ogDescription' => 'string',
        'extraMetaData' => 'string',
        'ogImage' => '\NFQ\KunstmaanRestApi\PhpClient\Model\Media'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'metaTitle' => null,
        'metaDescription' => null,
        'metaAuthor' => null,
        'metaRobots' => null,
        'ogType' => null,
        'ogTitle' => null,
        'ogDescription' => null,
        'extraMetaData' => null,
        'ogImage' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'metaTitle' => false,
        'metaDescription' => false,
        'metaAuthor' => false,
        'metaRobots' => false,
        'ogType' => false,
        'ogTitle' => false,
        'ogDescription' => false,
        'extraMetaData' => false,
        'ogImage' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'metaTitle' => 'metaTitle',
        'metaDescription' => 'metaDescription',
        'metaAuthor' => 'metaAuthor',
        'metaRobots' => 'metaRobots',
        'ogType' => 'ogType',
        'ogTitle' => 'ogTitle',
        'ogDescription' => 'ogDescription',
        'extraMetaData' => 'extraMetaData',
        'ogImage' => 'ogImage'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'metaTitle' => 'setMetaTitle',
        'metaDescription' => 'setMetaDescription',
        'metaAuthor' => 'setMetaAuthor',
        'metaRobots' => 'setMetaRobots',
        'ogType' => 'setOgType',
        'ogTitle' => 'setOgTitle',
        'ogDescription' => 'setOgDescription',
        'extraMetaData' => 'setExtraMetaData',
        'ogImage' => 'setOgImage'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'metaTitle' => 'getMetaTitle',
        'metaDescription' => 'getMetaDescription',
        'metaAuthor' => 'getMetaAuthor',
        'metaRobots' => 'getMetaRobots',
        'ogType' => 'getOgType',
        'ogTitle' => 'getOgTitle',
        'ogDescription' => 'getOgDescription',
        'extraMetaData' => 'getExtraMetaData',
        'ogImage' => 'getOgImage'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('metaTitle', $data ?? [], null);
        $this->setIfExists('metaDescription', $data ?? [], null);
        $this->setIfExists('metaAuthor', $data ?? [], null);
        $this->setIfExists('metaRobots', $data ?? [], null);
        $this->setIfExists('ogType', $data ?? [], null);
        $this->setIfExists('ogTitle', $data ?? [], null);
        $this->setIfExists('ogDescription', $data ?? [], null);
        $this->setIfExists('extraMetaData', $data ?? [], null);
        $this->setIfExists('ogImage', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets metaTitle
     *
     * @return string|null
     */
    public function getMetaTitle()
    {
        return $this->container['metaTitle'];
    }

    /**
     * Sets metaTitle
     *
     * @param string|null $metaTitle metaTitle
     *
     * @return self
     */
    public function setMetaTitle($metaTitle)
    {
        if (is_null($metaTitle)) {
            throw new \InvalidArgumentException('non-nullable metaTitle cannot be null');
        }
        $this->container['metaTitle'] = $metaTitle;

        return $this;
    }

    /**
     * Gets metaDescription
     *
     * @return string|null
     */
    public function getMetaDescription()
    {
        return $this->container['metaDescription'];
    }

    /**
     * Sets metaDescription
     *
     * @param string|null $metaDescription metaDescription
     *
     * @return self
     */
    public function setMetaDescription($metaDescription)
    {
        if (is_null($metaDescription)) {
            throw new \InvalidArgumentException('non-nullable metaDescription cannot be null');
        }
        $this->container['metaDescription'] = $metaDescription;

        return $this;
    }

    /**
     * Gets metaAuthor
     *
     * @return string|null
     */
    public function getMetaAuthor()
    {
        return $this->container['metaAuthor'];
    }

    /**
     * Sets metaAuthor
     *
     * @param string|null $metaAuthor metaAuthor
     *
     * @return self
     */
    public function setMetaAuthor($metaAuthor)
    {
        if (is_null($metaAuthor)) {
            throw new \InvalidArgumentException('non-nullable metaAuthor cannot be null');
        }
        $this->container['metaAuthor'] = $metaAuthor;

        return $this;
    }

    /**
     * Gets metaRobots
     *
     * @return string|null
     */
    public function getMetaRobots()
    {
        return $this->container['metaRobots'];
    }

    /**
     * Sets metaRobots
     *
     * @param string|null $metaRobots metaRobots
     *
     * @return self
     */
    public function setMetaRobots($metaRobots)
    {
        if (is_null($metaRobots)) {
            throw new \InvalidArgumentException('non-nullable metaRobots cannot be null');
        }
        $this->container['metaRobots'] = $metaRobots;

        return $this;
    }

    /**
     * Gets ogType
     *
     * @return string|null
     */
    public function getOgType()
    {
        return $this->container['ogType'];
    }

    /**
     * Sets ogType
     *
     * @param string|null $ogType ogType
     *
     * @return self
     */
    public function setOgType($ogType)
    {
        if (is_null($ogType)) {
            throw new \InvalidArgumentException('non-nullable ogType cannot be null');
        }
        $this->container['ogType'] = $ogType;

        return $this;
    }

    /**
     * Gets ogTitle
     *
     * @return string|null
     */
    public function getOgTitle()
    {
        return $this->container['ogTitle'];
    }

    /**
     * Sets ogTitle
     *
     * @param string|null $ogTitle ogTitle
     *
     * @return self
     */
    public function setOgTitle($ogTitle)
    {
        if (is_null($ogTitle)) {
            throw new \InvalidArgumentException('non-nullable ogTitle cannot be null');
        }
        $this->container['ogTitle'] = $ogTitle;

        return $this;
    }

    /**
     * Gets ogDescription
     *
     * @return string|null
     */
    public function getOgDescription()
    {
        return $this->container['ogDescription'];
    }

    /**
     * Sets ogDescription
     *
     * @param string|null $ogDescription ogDescription
     *
     * @return self
     */
    public function setOgDescription($ogDescription)
    {
        if (is_null($ogDescription)) {
            throw new \InvalidArgumentException('non-nullable ogDescription cannot be null');
        }
        $this->container['ogDescription'] = $ogDescription;

        return $this;
    }

    /**
     * Gets extraMetaData
     *
     * @return string|null
     */
    public function getExtraMetaData()
    {
        return $this->container['extraMetaData'];
    }

    /**
     * Sets extraMetaData
     *
     * @param string|null $extraMetaData extraMetaData
     *
     * @return self
     */
    public function setExtraMetaData($extraMetaData)
    {
        if (is_null($extraMetaData)) {
            throw new \InvalidArgumentException('non-nullable extraMetaData cannot be null');
        }
        $this->container['extraMetaData'] = $extraMetaData;

        return $this;
    }

    /**
     * Gets ogImage
     *
     * @return \NFQ\KunstmaanRestApi\PhpClient\Model\Media|null
     */
    public function getOgImage()
    {
        return $this->container['ogImage'];
    }

    /**
     * Sets ogImage
     *
     * @param \NFQ\KunstmaanRestApi\PhpClient\Model\Media|null $ogImage ogImage
     *
     * @return self
     */
    public function setOgImage($ogImage)
    {
        if (is_null($ogImage)) {
            throw new \InvalidArgumentException('non-nullable ogImage cannot be null');
        }
        $this->container['ogImage'] = $ogImage;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


